use admon01
go

update CI_FACTURA set SIT_CONCILIA_CXC = 'NC' WHERE F_OPERACION >= '20190301' AND F_OPERACION <= '20190331'

UPDATE CI_MOVTO_BANCARIO SET SIT_CONCILIA_BANCO = 'NC' WHERE ANO_MES = '201903' AND CVE_CHEQUERA = 'MDB437'

delete from [dbo].[CI_CONCILIA_C_X_C]


update CI_CUENTA_X_PAGAR set SIT_CONCILIA_CXP = 'NC' WHERE F_CAPTURA >= '20190301' AND F_CAPTURA <= '20190331'

UPDATE CI_MOVTO_BANCARIO SET SIT_CONCILIA_BANCO = 'NC' WHERE ANO_MES = '201903' AND CVE_CHEQUERA = 'MDB437'

delete from CI_CONCILIA_C_X_P



SELECT * FROM CI_CONCILIA_C_X_C

select count(*) from CI_CONCILIA_C_X_C

SELECT * FROM CI_FACTURA WHERE ID_CONCILIA_CXC IN (807,809,810)
SELECT * FROM CI_MOVTO_BANCARIO WHERE ANO_MES = '201903' and CVE_CHEQUERA = 'MDB437'
-- ID_MOVTO_BANCARIO  IN (2957,2958,2977)
--PAGO RECIBIDO DE    14970107493 TRANSF.  Referencia Númerica: DEPOS D049073114 Autorización: 00021582

drop type

USE [ADMON01]
GO
drop type [dbo].[TMOVBANCFACT]
/****** Object:  UserDefinedTableType [dbo].[TMOVBANCFACT]    Script Date: 07/10/2019 01:44:42 p. m. ******/
CREATE TYPE [dbo].[TMOVBANCFACT] AS TABLE(
	[CVE_EMPRESA] [varchar](4) NULL,
	[ANO_PERIODO] [varchar](6) NULL,
	[ID_MOVTO_BANCARIO] [int] NULL,
	[CVE_TIPO] [varchar](1) NULL,
	[REFERENCIA] [varchar](20) NULL,
	[CVE_CHEQUERA] [varchar](6) NULL,
	[SERIE] [varchar](6) NULL,
	[ID_CXC] [int] NULL
)
GO





