USE [ADMON01]
GO
/****** Calcula Cuotas Obrero Patronales ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
IF  EXISTS( SELECT 1 FROM ADMON01.sys.procedures WHERE Name =  'spConcSatCxP')
BEGIN
  DROP  PROCEDURE spConcSatCxP
END
GO
--EXEC spConcSatCxP
CREATE PROCEDURE [dbo].[spConcSatCxP] 

AS
BEGIN
  DECLARE  @k_cve_no_conc  varchar(1) = 'P'

  SELECT 
  ANO_MES_PROC as 'ANO PROCESO',
  RFC_EMISOR as 'RFC EMISOR',
  NOM_EMISOR as 'NOM. EMISOR',
  RFC_RECEPTOR as 'RFC RECEPTOR',
  NOM_RECEPTOR as 'NOM. RECEPTOR',
  F_EMISION as 'F. EMISION',
  F_CERTIFICACION as 'F. CERTIFICACION',
  IMP_FACTURA as 'IMP. FACTURA',
  EFECTO_COMPROB as 'EFEC. COMPROB.',
  ESTATUS as 'ESTATUS',
  F_CANCELACION as 'F. CANCELACION',
  ID_CXP as 'ID. CXP',
  ID_CXP_DET as 'ID. DETALLE',
  SIT_CONCILIA as 'SIT. CONCILIA',
  B_AUTOMATICO as 'CARGA AUTOMATICA'
  FROM CI_SAT_CXP EFECTO_COMPROB WHERE EFECTO_COMPROB <> @k_cve_no_conc ORDER BY ANO_MES_PROC
END

