USE [ADMON01]
GO
/****** Calcula Cuotas Obrero Patronales ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
IF  EXISTS( SELECT 1 FROM ADNOMINA01.sys.procedures WHERE Name =  'spConcSatCxC')
BEGIN
  DROP  PROCEDURE spConcSatCxC
END
GO
--EXEC spConcSatCxC '201901'
CREATE PROCEDURE [dbo].[spConcSatCxC] 
(
@pAnoPeriodo      varchar(6)
)
AS
BEGIN
  DECLARE  @k_cve_no_conc  varchar(1) = 'P'

  SELECT 
  ANO_MES_PROC as 'ANO PROCESO',
  RFC_EMISOR as 'RFC EMISOR',
  NOM_EMISOR as 'NOM. EMISOR',
  RFC_RECEPTOR as 'RFC RECEPTOR',
  NOM_RECEPTOR as 'NOM. RECEPTOR',
  F_EMISION as 'F. EMISION',
  F_CERTIFICACION as 'F. CERTIFICACION',
  IMP_FACTURA as 'IMP. FACTURA',
  EFECTO_COMPROB as 'EFEC. COMPROB.',
  ESTATUS as 'ESTATUS',
  F_CANCELACION as 'F. CANCELACION',
  ID_CONCILIA_CXC as 'ID. FACTURA',
  SIT_CONCILIA as 'SIT. CONCILIA',
  B_AUTOMATICO as 'CARGA AUTOMATICA'
  FROM CI_SAT_FACTURA WHERE ANO_MES_PROC= @pAnoPeriodo AND EFECTO_COMPROB <> @k_cve_no_conc
END

