USE [ADMON01]
GO
/****** Calcula Cuotas Obrero Patronales ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
IF  EXISTS( SELECT 1 FROM ADMON01.sys.procedures WHERE Name =  'spConcSatCxP')
BEGIN
  DROP  PROCEDURE spConcSatCxP
END
GO
--EXEC spRepConcSatCxP
CREATE PROCEDURE [dbo].[spRepConcSatCxP] 

AS
BEGIN
  DECLARE  @k_cve_no_conc1  varchar(1) = 'P',
           @k_cve_no_conc2  varchar(1) = 'E'

  SELECT 
  ANO_MES_PROC as 'ANO/MES PROC',
  RFC_EMISOR as 'RFC EMISOR',
  NOM_EMISOR as 'NOM. EMISOR',
  RFC_RECEPTOR as 'RFC RECEPTOR',
  NOM_RECEPTOR as 'NOM. RECEPTOR',
  F_EMISION as 'F. EMISION',
  F_CERTIFICACION as 'F. CERTIFICACION',
  IMP_FACTURA as 'IMP. FACTURA',
  EFECTO_COMPROB as 'EFEC. COMPROB.',
  ESTATUS as 'ESTATUS',
  F_CANCELACION as 'F. CANCELACION',
  ID_CXP as 'ID. CXP',
  ID_CXP_DET as 'ID. DETALLE',
  SIT_CONCILIA as 'SIT. CONCILIA',
  B_AUTOMATICO as 'CARGA AUTOMATICA',
  ANO_MES_CONC as 'ANO/MES CONC',
  CVE_CONC_MAN as 'CVE. CONC. MAN'
  FROM CI_SAT_CXP EFECTO_COMPROB WHERE EFECTO_COMPROB NOT IN  (@k_cve_no_conc1,@k_cve_no_conc2) ORDER BY ANO_MES_PROC
END

