SELECT m.F_OPERACION, m.DESCRIPCION, m.CVE_CHEQUERA, m.IMP_TRANSACCION FROM CI_TIPO_MOVIMIENTO t, CI_MOVTO_BANCARIO m WHERE t.CVE_TIPO_MOVTO  =  'RET' AND
t.CVE_TIPO_MOVTO  =  m.CVE_TIPO_MOVTO   AND
dbo.fnArmaAnoMes (YEAR(m.F_OPERACION), MONTH(m.F_OPERACION))  = '201801' 
