USE [ADMON01]
GO

SET ANSI_NULLS ON

GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
--exec spConcFacturacion 'CU', 'MARIO', '201804', 12, 361, ' ', ' '
ALTER PROCEDURE [dbo].[spConCuCoCxc]   @pCveEmpresa varchar(4), @pAnoMes  varchar(6)
AS
BEGIN
  SELECT 
  CVE_F_MONEDA, 
  F_OPERACION, 
  ID_CLIENTE, 
  NOMBRE_CLIENTE, 
  CVE_EMPRESA, 
  SERIE,
  ID_CXC, 
  DESC_PRODUCTO_FACT,
  IMP_F_NETO,
  TIPO_CAMBIO,
  IMP_PESOS,
  TX_NOTA_COBRANZA
  FROM CI_CUCO_C_X_C WHERE ANO_MES = @pAnoMes ORDER BY CVE_F_MONEDA, F_OPERACION
END