USE [ADMON01]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO

ALTER PROCEDURE spActPctTarea @pIdTarea numeric(9), @pAvance int
AS
BEGIN
  UPDATE FC_GEN_TAREA SET PCT_AVANCE = @pAvance  WHERE ID_TAREA = @pIdTarea
END
