USE [ADMON01]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON
GO
IF  EXISTS( SELECT 1 FROM ADMON01.sys.procedures WHERE Name =  'spIncFolio')
BEGIN
  DROP  PROCEDURE spIncFolio
END
GO
CREATE PROCEDURE [dbo].[spIncFolio] @pCveFolio varchar(4)
AS
BEGIN
  UPDATE CI_FOLIO SET NUM_FOLIO = NUM_FOLIO + 1  WHERE CVE_FOLIO = @pCveFolio
END


