USE [MASTER]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
USE master
ALTER DATABASE ADNOMINA01 SET OFFLINE WITH ROLLBACK IMMEDIATE
GO
--EXECUTE spRestore 'ADNOMINA0120190124.BAK'
ALTER PROCEDURE spRestore @pNombre nvarchar(50) 
AS
BEGIN

  DECLARE  @path nvarchar(100)

  SELECT
  SERVERPROPERTY('MachineName') AS [ServerName], 
  SERVERPROPERTY('ServerName') AS [ServerInstanceName], 
  SERVERPROPERTY('InstanceName') AS [Instance], 
  SERVERPROPERTY('Edition') AS [Edition],
  SERVERPROPERTY('ProductVersion') AS [ProductVersion], 
  Left(@@Version, Charindex('-', @@version) - 2) As VersionName    

  SET @path  = LTRIM(N'C:\RESPALDOSMLP\' + @pNombre)

  SELECT @path

  RESTORE HEADERONLY FROM DISK = @path
  RESTORE FILELISTONLY from DISK = @path
  RESTORE LABELONLY from DISK = @path

  IF CONVERT(NVARCHAR(100),(SELECT SERVERPROPERTY('MachineName'))) = 'MLOPEZP' 
  BEGIN
    SELECT ' EJECUTA RESTORE '
--    DROP DATABASE ADMON01 
    RESTORE DATABASE ADNOMINA01 FROM DISK=  @path
    WITH FILE = 1, REPLACE,
    RECOVERY, 
    MOVE 'ADNOMINA01' TO  N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ADNOMINA01.mdf',
    MOVE 'ADNOMINA01_log' TO N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ADNOMINA01.ldf' 
    SELECT ' TERMINO CORRECTAMENTE '
  END
  ELSE
  BEGIN
    SELECT ' EL RESTORE NO FUE EJECUTADO'
  END
END

