USE ADMON01
GO
ALTER TABLE CI_CUENTA_X_PAGAR ADD CVE_MOT_CONCIL varchar(2) 
USE ADINFRA01
GO
ALTER TABLE CI_CUENTA_X_PAGAR ADD B_FACTURA bit
ALTER TABLE CI_CUENTA_X_PAGAR ADD CVE_MOT_CONCIL varchar(2) 